// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOv1iqZLuMtoOlPnehDbonzipB0izq9Ro',
    appId: '1:603976194765:web:bd07e309d9e1aa1d47a784',
    messagingSenderId: '603976194765',
    projectId: 'mondecare-3b42f',
    authDomain: 'mondecare-3b42f.firebaseapp.com',
    storageBucket: 'mondecare-3b42f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcyD_SFHps4fx3ZJfZPN8OR_tk_nAU_WM',
    appId: '1:603976194765:android:e13d1b019fd3117547a784',
    messagingSenderId: '603976194765',
    projectId: 'mondecare-3b42f',
    storageBucket: 'mondecare-3b42f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI9SXa9U2zKJKeI5GDu59s9fRoMZxlgQ',
    appId: '1:603976194765:ios:915ddf799024ffeb47a784',
    messagingSenderId: '603976194765',
    projectId: 'mondecare-3b42f',
    storageBucket: 'mondecare-3b42f.appspot.com',
    iosBundleId: 'com.example.mondecare',
  );
}
